/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class onyxplatform_test_NativeMergeFn */

#ifndef _Included_onyxplatform_test_NativeMergeFn
#define _Included_onyxplatform_test_NativeMergeFn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     onyxplatform_test_NativeMergeFn
 * Method:    merge
 * Signature: (Lclojure/lang/IPersistentMap;Lclojure/lang/IPersistentMap;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_NativeMergeFn_merge
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
