/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class onyxplatform_test_NativePassFn */

#ifndef _Included_onyxplatform_test_NativePassFn
#define _Included_onyxplatform_test_NativePassFn
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
