/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class onyxplatform_test_NativeAssocFn */

#ifndef _Included_onyxplatform_test_NativeAssocFn
#define _Included_onyxplatform_test_NativeAssocFn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     onyxplatform_test_NativeAssocFn
 * Method:    assocObj
 * Signature: (Lclojure/lang/IPersistentMap;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_NativeAssocFn_assocObj
  (JNIEnv *, jobject, jobject);

/*
 * Class:     onyxplatform_test_NativeAssocFn
 * Method:    assocInt
 * Signature: (Lclojure/lang/IPersistentMap;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_NativeAssocFn_assocInt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     onyxplatform_test_NativeAssocFn
 * Method:    assocFloat
 * Signature: (Lclojure/lang/IPersistentMap;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_NativeAssocFn_assocFloat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     onyxplatform_test_NativeAssocFn
 * Method:    assocDouble
 * Signature: (Lclojure/lang/IPersistentMap;)V
 */
JNIEXPORT void JNICALL Java_onyxplatform_test_NativeAssocFn_assocDouble
  (JNIEnv *, jobject, jobject);

/*
 * Class:     onyxplatform_test_NativeAssocFn
 * Method:    assocBool
 * Signature: (Lclojure/lang/IPersistentMap;)V
 */
JNIEXPORT void JNICALL Java_onyxplatform_test_NativeAssocFn_assocBool
  (JNIEnv *, jobject, jobject);

/*
 * Class:     onyxplatform_test_NativeAssocFn
 * Method:    assocStr
 * Signature: (Lclojure/lang/IPersistentMap;)V
 */
JNIEXPORT void JNICALL Java_onyxplatform_test_NativeAssocFn_assocStr
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
