/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class onyxplatform_test_NativeGetFn */

#ifndef _Included_onyxplatform_test_NativeGetFn
#define _Included_onyxplatform_test_NativeGetFn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     onyxplatform_test_NativeGetFn
 * Method:    getObj
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_NativeGetFn_getObj
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     onyxplatform_test_NativeGetFn
 * Method:    getInt
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_onyxplatform_test_NativeGetFn_getInt
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     onyxplatform_test_NativeGetFn
 * Method:    getFloat
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_onyxplatform_test_NativeGetFn_getFloat
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     onyxplatform_test_NativeGetFn
 * Method:    getDouble
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_onyxplatform_test_NativeGetFn_getDouble
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     onyxplatform_test_NativeGetFn
 * Method:    getLong
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_onyxplatform_test_NativeGetFn_getLong
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     onyxplatform_test_NativeGetFn
 * Method:    getBool
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_onyxplatform_test_NativeGetFn_getBool
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     onyxplatform_test_NativeGetFn
 * Method:    getStr
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_onyxplatform_test_NativeGetFn_getStr
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
