/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class onyxplatform_test_NativeDissocFn */

#ifndef _Included_onyxplatform_test_NativeDissocFn
#define _Included_onyxplatform_test_NativeDissocFn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     onyxplatform_test_NativeDissocFn
 * Method:    dissoc
 * Signature: (Lclojure/lang/IPersistentMap;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_NativeDissocFn_dissoc
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
